add install step

diff --git a/.github/workflows/validate-theme.yml b/.github/workflows/validate-theme.yml
--- a/.github/workflows/validate-theme.yml
+++ b/.github/workflows/validate-theme.yml
@@ -35,8 +35,8 @@ jobs:
           node-version-file: '.nvmrc'
           cache: 'npm'
 
-      # - name: Install dependencies
-      #   run: npm ci
+      - name: Install dependencies
+        run: npm ci
 
       - name: Validate Themes
         id: validate_themes
@@ -50,17 +50,28 @@ jobs:
             exit 0
           else
             echo "Validating themes: $changes"
-            echo "node theme-utils.mjs validate-theme $changes"
+            echo "running exit 1"
             # node theme-utils.mjs validate-theme "$changes"
+
+            set +e
             output=$(node theme-utils.mjs validate-theme "$changes")
+            exit_code=$?
+            set -e
+
+            # Check the exit code
+            if [ $exit_code -ne 0 ]; then
+              echo "Command failed with exit code $exit_code."
+              echo "VALIDATION_FAILED=true" >> $GITHUB_ENV
+            fi
+
             echo "$output"
             echo "output=$output" >> $GITHUB_OUTPUT
           fi
           # node theme-utils.mjs validate-theme $(git diff --name-only HEAD^ -- ${{ env.PR_PATHS }} | awk -F/ '{print $1}' | uniq | paste -s -d, -)
 
-      - name: Set failed flag if theme validation failed
-        if: ${{ steps.validate_themes.outcome == 'failure' }}
-        run: echo "VALIDATION_FAILED=true" >> $GITHUB_ENV
+      # - name: Set failed flag if theme validation failed
+      #   if: ${{ steps.validate_themes.outcome == 'failure' }}
+      #   run: echo "VALIDATION_FAILED=true" >> $GITHUB_ENV
 
       - name: Find Comment
         uses: peter-evans/find-comment@v3
